//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autodesk.DesignScript.Geometry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autodesk.DesignScript.DSGeometry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the curve is not closed.
        /// </summary>
        internal static string CurveNotClosed {
            get {
                return ResourceManager.GetString("CurveNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the curve is not planar.
        /// </summary>
        internal static string CurveNotPlanar {
            get {
                return ResourceManager.GetString("CurveNotPlanar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the distance between {0} and {1} are not equal.
        /// </summary>
        internal static string DistanceNotEqual {
            get {
                return ResourceManager.GetString("DistanceNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t exist.
        /// </summary>
        internal static string DoesNotExist {
            get {
                return ResourceManager.GetString("DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} and the {1} are equal or at the same location.
        /// </summary>
        internal static string EqualGeometry {
            get {
                return ResourceManager.GetString("EqualGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate File: {0}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} is greater than {1}.
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} is invalid.
        /// </summary>
        internal static string InvalidArguments {
            get {
                return ResourceManager.GetString("InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the input {0} is invalid for {1}.
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot intersect with {1}.
        /// </summary>
        internal static string InvalidIntersect {
            get {
                return ResourceManager.GetString("InvalidIntersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot project on {1}.
        /// </summary>
        internal static string InvalidProjection {
            get {
                return ResourceManager.GetString("InvalidProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} and {1} are parallel for {2}.
        /// </summary>
        internal static string IsParallel {
            get {
                return ResourceManager.GetString("IsParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} is zero.
        /// </summary>
        internal static string IsZero {
            get {
                return ResourceManager.GetString("IsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} angle is zero.
        /// </summary>
        internal static string IsZeroAngle {
            get {
                return ResourceManager.GetString("IsZeroAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the distance between the {0} and the {1} is zero.
        /// </summary>
        internal static string IsZeroDistance {
            get {
                return ResourceManager.GetString("IsZeroDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the length is zero.
        /// </summary>
        internal static string IsZeroLength {
            get {
                return ResourceManager.GetString("IsZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the radius is zero.
        /// </summary>
        internal static string IsZeroRadius {
            get {
                return ResourceManager.GetString("IsZeroRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the input {0}  is zero.
        /// </summary>
        internal static string IsZeroVector {
            get {
                return ResourceManager.GetString("IsZeroVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} is less than {1}.
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} is less than zero.
        /// </summary>
        internal static string LessThanZero {
            get {
                return ResourceManager.GetString("LessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} is not equal to {2}.
        /// </summary>
        internal static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported for {1}.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} is null.
        /// </summary>
        internal static string NullArgument {
            get {
                return ResourceManager.GetString("NullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} operation failed.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} are coincident.
        /// </summary>
        internal static string PointsCoincident {
            get {
                return ResourceManager.GetString("PointsCoincident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} are colinear.
        /// </summary>
        internal static string PointsColinear {
            get {
                return ResourceManager.GetString("PointsColinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is sheared.
        /// </summary>
        internal static string Sheared {
            get {
                return ResourceManager.GetString("Sheared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set vertex color to SubDivisionMesh with SubDivisionLevel more than zero.
        /// </summary>
        internal static string VertexColorNotSupported {
            get {
                return ResourceManager.GetString("VertexColorNotSupported", resourceCulture);
            }
        }
    }
}
